### ISSUE TITLE
Are there any releases?

### ISSUE THREAD

**Issue by ChristianCiach** [3dcitydb/swingx-all#1]
Hi!

I need the binaries of this fine project (and swingx-ws, too), but I cannot find any jars.

By looking at your build.gradle files, it seems like you are planning to upload your artifacts to bintray, but your namespace seems to be empty: https://repo.jfrog.org/artifactory/libs-release-bintray/org/citydb/

Of course, I could fork and build it by myself, but it would be way easier if there were published releases available.

**Comment by clausnagel** [comment]
Hi @ChristianCiach, thanks for your message. This repo is just a copy of swingx due to inactivity of the original project. We use this repo only for the [Importer/Exporter](https://github.com/3dcitydb/importer-exporter) tool of the 3DCityDB. And we have fixed some bugs in swingx so that it works for this tool. The intention of this repo is not to generally maintain the swingx project and to provide regular releases. That's also why we have not published it on JCenter or Maven Central.

It's nevertheless available from bintray. This is how we use it for the Importer/Exporter.

```gradle
repositories {
    maven {
        url 'https://dl.bintray.com/3dcitydb/maven'
    }
}

dependencies {
    implementation ('org.citydb:swingx-ws:1.1.3') {
        transitive = false
    }
    implementation ('org.citydb:swingx-all:1.6.7') {
        transitive = false
    }
}
```

Maybe there are other forks of swingx which are more appropriate for your purpose? For example: https://github.com/ebourg/swingx

**Comment by ChristianCiach** [comment]
Thank you for your quick reply! 

Your fork contains a few fixes (like NPE fixes) that are not present in the latest official release of swingx-ws: https://mvnrepository.com/artifact/org.swinglabs/swingx-ws/1.0 That's why I am looking for a fork that contains these fixes so that we don't need maintain our own fork :)

Thanks for pointing me to other forks! I will take it look at these.
